language: perl
os:
  - linux
  # - osx

perl:
  - "5.30"
  - "5.28"
  - "5.26"
  - "5.24"
  - "5.22"
  - "5.20"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.24-shrplib"
  - "5.22-shrplib"
  - "5.20-shrplib"
  - "5.18-shrplib"

matrix:
  allow_features:
    - perl: blead
  include:
    - perl: 5.28
      env: COVERAGE=1

sudo: false

before_script:
  - coverage-setup

before_install:
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init
  - build-perl
  - perl -V
  - which perl cpanm
  - perl -MCPAN -e 'CPAN::Shell->install("App::cpanminus")'
  - which perl cpanm cpan
  - cpanm -n File::Fetch~0.56
  - build-dist
  - cd $BUILD_DIR

install:
  - sudo apt-get update -q
  - sudo apt-get install -y perl libio-aio-perl liblingua-en-nameparse-perl
  - sudo apt-get install libtest-most-perl libchi-perl
  - sudo apt-get install -y cpanminus libjson-perl libconfig-auto-perl libipc-system-simple-perl libautodie-perl libtext-csv-xs-perl liblog-log4perl-perl libtext-csv-perl
  - sudo apt-get install sqlite3 libdbi-perl libdbd-csv-perl liblocale-us-perl libdbd-sqlite3-perl
  - cpan-install --deps
  - cpan-install --coverage
  # - cpanm -n Devel::Cover::Report::Coveralls Test::Script Test::Pod::Spelling::CommonMistakes Test::Portability::Files Test::Taint Test::Carp DBD::SQLite DBI CHI Test::Carp Test::Without::Module
  - cpanm -n Devel::Cover::Report::Coveralls Locale::Country Test::Pod::Spelling::CommonMistakes FCGI::Buffer Log::WarnDie

script:
  # perl Makefile.PL && make && cover -test -report coveralls
  - perl Makefile.PL && make && prove -l -j$(test-jobs) $(test-files)

after_success:
  - coverage-report
